apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
    selector:
        app: order
    ports:
      - name: grpc
        protocol: TCP
        port: 8080
        targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels:
        service: order
    spec:
      initContainers:
        - name: postgresql-check
          image: busybox:1.28
          command: ["sh", "-c", "until pg_isready -h postgresql -p 5432 -U microservices; do echo waiting for postgresql; sleep 5; done;"]
      containers:
        - name: order
          image: order
          env:
            - name: APPLICATION_PORT
              value: "8080"
            - name: PAYMENT_SERVICE_URL
              value: "payment:8081"
            - name: env
              value: "prod"
            - name: DATA_SOURCE_URL
              value: "postgresql://ecommdb_root:s3cr3t@hostname:port/orders"
          ports:
            - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: order
spec:
  rules:
    - http:
        paths:
          - path: /Order
            pathType: Prefix
            backend:
              service:
                name: order
                port:
                  number: 8080
  tls:
    - hosts:
        - ingress.local
      secretName: order-tls