apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: postgres
resources:
  - statefulset.yaml
#  - pvc.yaml
  - configmap.yaml
  - service.yaml

secretGenerator:
  - envs:
      - postgres-credentials.env
    name: postgres-credentials